### ISSUE TITLE
pli-tv-bu-vb-ss3/en: move horizontal rule

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1378]
Please move the rule from after to before headings at the following segments:
3.3.0
3.4.0
3.5.0

And:

pli-tv-bu-vb-ss4/en: segment 3.1.23.0

**Comment by sujato** [comment]
Okay, I have removed the `<hr>` tags.

However, as a rule (get it? `hr` is "horizontal rule" … never mind!) the `<hr>` tag is intended to create a "thematic break" in places where there is no heading. So it should not be used together with any heading, thus I have simply removed them rather than shifting them.

Also, just to be clear, there is no separate HTML file for translations. There is one HTML template that is used for root and all translations.
