### ISSUE TITLE
Problem in root text

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1423]
pli-tv-bi-vb-ss13: in this rule the heading in the root text is different form all other rules. It reads:

> Saṅghādisesā 13: Dutiya­pāpa­samā­cāra­sikkhāpada

In other places the class of the rule (Saṅghādisesā) at the beginning is missing. They begin with the rule number.

In the _bhikkhu saṅghādisesas_ and _pārājikas_ even the numbers are missing. (For _bhikkhu pārājika_ 1, the number is missing also in the translated text.) Should this be made consistent?

**Comment by sujato** [comment]
Yes, it should be consistent.

- added number to pli-tv-bi-vb-ss13
- added number to bu-pj1 (this is a complex case, as it rather clumsily includes the veranjakanda. Just this morning, I adjusted the way the headings are handled, as it was gumming up our publications project. Check it out!)

I think the remainder of the bu-ss and bu-pj have numbers already?

*** 

The larger issue is the handling of headings and how it will work with the Publications. I have made some adjustments to the Suttas, and in the Vinaya, have added stub files for the bi-pj1-4, so that the system can handle them. 

There have been one or two niggling problems that have stopped the Vinaya publications files from compiling, and hopefully the above fixes will solve that. I'm expecting to get the compiled files today and will share with you.

This is just a first draft. We'll have to look at how the system ends up handling the headings, whether they present well, and so on.

As a general rule, I want to keep things as consistent as possible, then the code is simple and robust. So preferably we'll make changes in the data. If that's not possible, then we can adjust the programming. But the more exceptions we make, the more complexity, the more bugs, the more hassle.

Anyway let's see what the first pass looks like and map out a course from there.

***

### an ideal world of fairy floss and unicorns

In the Suttas, I have settled on an approach for publications that essentially has three components per heading:

- UID
- translated title
- root title

eg.

- DN 9 
- With Poṭṭhapāda 
- Poṭṭhapādasutta 

We can then present these three in different ways per context, eg. in the Table of Contents, sutta headings, etc.

It seems to me that this would work for the Vinaya as well. Each rule, or chapter of the Khandhakas, would have three items.  Since the Vinaya rules are frequently referred to by the rule name in Pali + number, it seems to me that it would be better to use this rather than the acronym (Pli Tv Bu Pj 1), which is pretty obscure.

- Bhikkhu Pārājika 1
- On Sexual Intercourse
- Methunadhamma
