### ISSUE TITLE
sc-audio change bi-sk1-75 to sk1 and sk75

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#1780]
Because of the requirements of publications, I have split bi-sk1-75 into its two files, sk1 and sk75.

This change is reflected throughout.

However sc-data/additional-info/available_voices.json still has the old listing. I've no idea what to do, but anyway, know that we no longer use this at all.

**Comment by firepick1** [comment]
Thanks, Bhante. I've confirmed that our audio sites cannot speak these at the moment. Our content pipeline is partially blocked because of the Vuetify2/Vuetify3 upgrade, which will take months. Vuetify3 is still in beta and unstable. Unfortunately, this severely constrains our content update capabilities.
