### ISSUE TITLE
Add check for bilara data texts

### ISSUE THREAD

**Issue by alple** [suttacentral/bilara-data#181]
Leveraging github actions add check for bilara data.

With every Pull Request bilara-data texts will be check for consistency - duplicated uid, references and alike (full list of check coming)

See https://github.com/suttacentral/bilara-data/pull/185

**Comment by sujato** [comment]
Here are some thoughts for improving the scripts.

## `check_migration`

By far the most important change would be reducing the scope of the text chunks in migration_checking script. It should test for the *minimum possible range* of `ms` IDs. Currently, I am not sure exactly how it concatenates text, but it seems to do it per-file or something. This results in unworkably huge chunks, up to 43,000 words. The logic should be something like this:

- When `ms` ID in bilara-data matches ID in `ms`, start the chunk of text.
- Continue the chunk of text until the next `ms` ID in bilara-data.
- Stop the current chunk.
- Start new chunk from the matching IDs.

The following could also be improved, we should aim for zero false positives.

- [ ] Script does not currently alias ṃ and ṁ. This will show many bugs unless you replace: ṃ --> ṁ, ṁg --> ṅg, ṁk --> ṅk.
- [ ] `File with the key: 'sn48.147-158' is missing in the root or reference directory` 4 false positives of this error.
- [ ]  10 false positives of "contains many ms ids" or "does not contain ms ids"
- [ ]  86 false positives in /migration_differences/extra_words_summary.

## `run_all_checks`

Here are the other issues for which there are currently error messages when running `run_all_checks`. They should be fixed with the aim to have zero false positives.

- [ ] **`duplicated versus error`**: (sic! Versus = “verses”) Currently `BilaraReferenceAggregate` reports 11 duplicate adjacent segments. However they are not errors, the text is meant to duplicate. The script should ignore these cases and not show an error: 'an2.37:8.1', 'pli-tv-bu-vb-pc34:1.1.16', 'pli-tv-bu-vb-pc34:1.1.24', 'pli-tv-bu-vb-pc34:1.1.9', 'pli-tv-bu-vb-pc34:1.2.5', 'pli-tv-kd7:12.1.12', 'pli-tv-kd7:12.1.18', 'pli-tv-kd7:12.1.25', 'pli-tv-kd7:12.1.32', 'pli-tv-kd7:12.1.4', 'pli-tv-pvr7:96.21'.
- [ ] **`not enough values to unpack`**: Currently `BilaraReferenceAggregate` throws an error for the translation of blurbs into German. Note that we have blurbs for things that are not suttas. The blurb IDs are in root/en/blurb.
- [ ] **`No language detected`**: Currently `BilaraReferenceAggregate` relies on a hard-coded list of languages at /src/sutta_processor/application/domain_models/bilara_translation/root.py. This is brittle, as new languages will be added. Languages should be derived from `_publication.json`.
- [ ] **`Key 'sa12.20:2.2' was not found in 'BilaraRootAggregate'`**: `BilaraVariantAggregate` reports this error, yet the root is in fact present. This is a Chinese root text, root texts in any language should be accepted.
- [ ] **`get_wrong_uid_with_arrow`**: Currently `BilaraVariantAggregate` reports 56 `get_wrong_uid_with_arrow` errors. These are all due to ellipsis (…) in the variant. The variants sometimes abbreviate long text, indicated by ellipsis. So only compare what is before the ellipsis, eg: 
   - `Word 'Kimagghati … taṇḍulanāḷikā”ti' not found in the base verse: '{'ja5:1.1': '“Kimagghati taṇḍulanāḷikāyaṁ,'}'`
   - Check "Kimagghati" only.
- [ ] **`get_unordered_segments`**: Currently `BilaraVariantAggregate` reports 7 ordered segments, however the sequence is in fact correct.

**Comment by sujato** [comment]
See also:

https://github.com/suttacentral/bilara/issues/21

**Comment by sujato** [comment]
See discussion here: https://discourse.suttacentral.net/t/helping-out-with-server-development/18599/47
