### ISSUE TITLE
folders and helpers and scripts, oh my!

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#217]
I'm just wondering what the best place is for keeping the various scripts and things. It seems currently we have two folders, `.scripts` and `.helpers`, but where do they belong?

May I propose something along the following lines?

- `.helpers` is for user-facing utilities that might be used by third-party apps. It would thus include bilara i/o, which should have its own subdirectory. It should live in the `published` branch.
- `.scripts` would include anything that is purely for internal use. It should live in the `unpublished` branch. It should have two main subdirectories:
    - `utility` for anything that makes stuff work
    - `analysis` for the analytic scripts developed by STXnext, which are intended to be run via Github Actions to ensure data integrity. See #181 

@blake-sc @firepick1 @cuboids

**Comment by firepick1** [comment]
Interesting proposal! It does make sense for .helpers to be user facing. The examples certainly have been helpful to users. And it makes sense to keep scripts away from users as unnecessary clutter.

The major problem to solve for scripts is garbage collection. Scripts tend to stick around like weeds and tend to be permanent unless deleted. Because of this I think we should organize according to degree of use. A "production" script would be used actively for the foreseeable future. A "project" script would be tied to a specific project such as "segment-renumbering". Projects are more naturally ephemeral and provide a context for script use. Under "projects", we could, for example have "cluster-analysis" or "word-length-analysis", etc.

**Comment by sujato** [comment]
Okay, so it seems we need a few directories inside `/.scripts`. Obviously we don't need to solve all problems now, but maybe:

```
  /.scripts
        /production
        /analysis
        /projects
```

Or perhaps simply `misc` for the last one? Not everything need be a well-defined project, it might just be something a developer put together one time.

**Comment by firepick1** [comment]
Ah. The dreaded "misc", a euphemism for "oops, I just need this for now, it's just a little script, not to worry, I'll take care of it when I'm done if I remember."

Actually, the scripts are all @blake-sc Blake's I believe. If I have any scripts, they would fall in the above lazyass category and should be probably deleted.

On an amusing note, I actually have adopted the practice of creating a "recycle" directory. Within that directory I delete anything that I don't recognize. That suggestion however might not work for a team of individuals lacking shared memory and intent.

Therefore, if we tell each other that on day X we will delete all scripts not reborn as (production, analysis and projects), then script 
life and death can proceed unimpeded. Any suffering that ensued would be due to mindlessness.

**Comment by sujato** [comment]
Indeed, if a script is not well documented then a dev is likely just want to start from scratch anyway.

**Comment by firepick1** [comment]
I decided to put pali-hyphenator.js in js-ebt rather than in bilara-data/.scripts/production. Bilara-data is a content repository and pali-hyphenator really belongs in a code repository with unit tests and all other code paraphernalia. I think of bilara-data scripts as having direct relevance only to bilara-data itself. I also didn't want bilara-data in node-modules since node-modules is for code, not data.

**Comment by sujato** [comment]
this seems mostly either done or out of date
