### ISSUE TITLE
edits on home_translation-id-site and interface_translation-id-site are not saved

### ISSUE THREAD

**Issue by renaldoaluska** [suttacentral/bilara-data#3009]
hello, sotthi hontu.

i notice that there are new updated sections to translate on both of these files (`interface_translation-id-site` and `home_translation-id-site`) but the translation is lost after page refresh, although "committed". and btw, sorry that it's been a long time since my last contribution (hectic weeks) :D 🙏

thanks!

**Comment by sabbamitta** [comment]
Greetings renaldoaluska!
Yes, this is indeed the case, and it is quite unfortunate. Every new item that has been added to the Bilara root files can only take effect when the Bilara server is rebooted, but the person who can do that isn't available at the moment.
So the only thing you could do would be to add the new items directly to your language folder in the repository in GitHub (unpublished branch) and create a pull request, if you feel comfortable with this process. Then we would ask @ihongda or @ccronje to merge the pull request.

**Comment by sabbamitta** [comment]
@ihongda I notice that the added items in the Home file refer to the new donations banner on the Home page, so perhaps this is rather important.

However I also notice that these three items have a different structure than the items in the rest of the file.

For all other items the "key" is a number in Bilara, and this number is prefixed by `home:` in the repository. So `1` in Bilara is `"home:1"` in the repository.

The three new items have no numbers but strings of text as "key" in Bilara, for example `donate:donate`. Does this have to become `"home:donate:donate"` in the repository? Or simply `"donate:donate"`?

So that in the repository we would either have
`"home:donate:donate": "[translation]",`
or
`"donate:donate": "[translation]",`
Which one would be correct?

**Comment by ihongda** [comment]
Ven @sabbamitta 
Since the donations banner is only a temporary element, I use donate: as a temporary key value to distinguish it. When the donations banner goes offline, these key values ​​will also be deleted.

**Comment by sabbamitta** [comment]
@renaldoaluska the Bilara server has just been rebooted, and you should now be able to translate and edit everything the normal way.
