### ISSUE TITLE
Create an exception for thin spaces \u2009 in translations

### ISSUE THREAD

**Issue by noeismet** [suttacentral/bilara-data#3266]
I am aware that in the documentation it is stated to never put any no-break space in translations. However, in French there are many places where we should normally place thin spaces. Now, I didn't mind until I spotted many instances in SuttaCentral where the punctuation is pushed to the next line, and it doesn't look good, especially when it comes to `! ? » ›` being alone on that line. 
I tried to put it as `\u2009` in my translation of MN12, and it worked well in Bilara, but once published, Nlakkhana removed them. 

Is this something we could address? 🙏

**Comment by thesunshade** [comment]
It's good that you bring this up. I have some vague memory that Bhante @sujato had given approval for using these according to language specific standards. Perhaps that didn't make it all the way through to fixing Nilakkhana.

In my opinion, it's better to proactively set language specific standards and code them in. Otherwise as new languages are added there may be problems that slip by.

For anyone like me who might just be curious, it *appears* that the scripts for nilakkhana are here, not in this repo:

https://github.com/suttacentral/sc-data/tree/master/sc_bilara_data/.nilakkhana

I'm just guessing, but part of the problem may be that Nilakkhana isn't able to tell fr files from en.

**Comment by noeismet** [comment]
> I'm just guessing, but part of the problem may be that Nilakkhana isn't able to tell fr files from en.

Thank you for your reply @thesunshade. Yes, I was looking into the nilakkhana files to see if that would be an easy fix, but in any cases I don't have a hand on them. I wonder if @ihongda and @ccronje may be able to comment on this?
